<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="app_logging/tests/apis/test_customer_device_context.py" name="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI-20220725104740" skipped="0" tests="9" time="2.389" timestamp="2022-07-25T10:50:34">
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="59" name="test_create_customer_device_context_api_fail_bad_schema" time="0.376" timestamp="2022-07-25T10:50:32">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="97" name="test_create_customer_device_context_api_fail_missing_device_id" time="0.240" timestamp="2022-07-25T10:50:32">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="36" name="test_create_customer_device_context_api_pass" time="0.359" timestamp="2022-07-25T10:50:33">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="32" name="test_list_is_not_permissible" time="0.214" timestamp="2022-07-25T10:50:33">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="25" name="test_unallowed_detail_methods" time="0.279" timestamp="2022-07-25T10:50:33">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="20" name="test_unauthorized" time="0.206" timestamp="2022-07-25T10:50:33">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="66" name="test_update_customer_device_context_device_id_case_insensitive" time="0.227" timestamp="2022-07-25T10:50:34">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="110" name="test_update_customer_device_context_when_device_id_customer_pair_exists" time="0.255" timestamp="2022-07-25T10:50:34">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="app_logging.tests.apis.test_customer_device_context.TestCustomersDeviceContextAPI" file="app_logging/tests/apis/test_customer_device_context.py" line="161" name="test_update_customer_device_context_when_device_id_user_profile_pair_exists" time="0.233" timestamp="2022-07-25T10:50:34">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
