<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="rentals/tests/apis/v3/test_scheduling.py" name="rentals.tests.apis.v3.test_scheduling.TestSRDateTimeAPIPeriodNotContiguousMidDayBreak-20220725105046" skipped="0" tests="4" time="2.883" timestamp="2022-07-25T10:58:34">
	<testcase classname="rentals.tests.apis.v3.test_scheduling.TestSRDateTimeAPIPeriodNotContiguousMidDayBreak" file="rentals/tests/apis/v3/test_scheduling.py" line="4099" name="test_end_dates" time="0.840" timestamp="2022-07-25T10:58:32">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="rentals.tests.apis.v3.test_scheduling.TestSRDateTimeAPIPeriodNotContiguousMidDayBreak" file="rentals/tests/apis/v3/test_scheduling.py" line="4118" name="test_end_times" time="0.702" timestamp="2022-07-25T10:58:33">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py:1369: RuntimeWarning: DateTimeField PlannedOutage.start_date_time received a naive datetime (2019-12-18 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py:1369: RuntimeWarning: DateTimeField PlannedOutage.start_date_time received a naive datetime (2019-12-19 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py:1369: RuntimeWarning: DateTimeField PlannedOutage.start_date_time received a naive datetime (2019-12-20 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py:1369: RuntimeWarning: DateTimeField PlannedOutage.start_date_time received a naive datetime (2019-12-21 00:00:00) while time zone support is active.
  RuntimeWarning)
]]>		</system-err>
	</testcase>
	<testcase classname="rentals.tests.apis.v3.test_scheduling.TestSRDateTimeAPIPeriodNotContiguousMidDayBreak" file="rentals/tests/apis/v3/test_scheduling.py" line="4068" name="test_start_dates" time="0.607" timestamp="2022-07-25T10:58:33">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="rentals.tests.apis.v3.test_scheduling.TestSRDateTimeAPIPeriodNotContiguousMidDayBreak" file="rentals/tests/apis/v3/test_scheduling.py" line="4074" name="test_start_times" time="0.734" timestamp="2022-07-25T10:58:34">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
