<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="hardware_sdk_otakeys/tests/test_interface.py" name="hardware_sdk_otakeys.tests.test_interface.TestAddRFID-20220725104740" skipped="0" tests="2" time="0.074" timestamp="2022-07-25T11:00:51">
	<testcase classname="hardware_sdk_otakeys.tests.test_interface.TestAddRFID" file="hardware_sdk_otakeys/tests/test_interface.py" line="37" name="test_add_rfid" time="0.042" timestamp="2022-07-25T11:00:51">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="hardware_sdk_otakeys.tests.test_interface.TestAddRFID" file="hardware_sdk_otakeys/tests/test_interface.py" line="52" name="test_add_rfid_with_application_error" time="0.033" timestamp="2022-07-25T11:00:51">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
